# Generated by Django 5.0.6 on 2024-05-23 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('intake_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('certificate_score', models.FloatField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_score_service.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_score_service.applicant')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_score_service.subject')),
            ],
        ),
    ]
