# Generated by Django 5.0.6 on 2024-05-20 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='is_approved',
        ),
    ]
